<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="53" started-at="2020-04-27T12:02:45 CDT" finished-at="2020-04-27T12:02:46 CDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="53" started-at="2020-04-27T12:02:45 CDT" finished-at="2020-04-27T12:02:46 CDT">
      <class name="testcases.ApplicationTest">
        <test-method status="PASS" signature="beforeallTest()[pri:0, instance:testcases.ApplicationTest@4f970963]" name="beforeallTest" is-config="true" duration-ms="9" started-at="2020-04-27T12:02:46 CDT" finished-at="2020-04-27T12:02:46 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeallTest -->
        <test-method status="PASS" signature="beforeeachmethod()[pri:0, instance:testcases.ApplicationTest@4f970963]" name="beforeeachmethod" is-config="true" duration-ms="0" started-at="2020-04-27T12:02:46 CDT" finished-at="2020-04-27T12:02:46 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeeachmethod -->
        <test-method status="FAIL" signature="doLogin()[pri:1, instance:testcases.ApplicationTest@4f970963]" name="doLogin" duration-ms="10" started-at="2020-04-27T12:02:46 CDT" finished-at="2020-04-27T12:02:46 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Error message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Error message
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcases.ApplicationTest.doLogin(ApplicationTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="aftereachmethod()[pri:0, instance:testcases.ApplicationTest@4f970963]" name="aftereachmethod" is-config="true" duration-ms="0" started-at="2020-04-27T12:02:46 CDT" finished-at="2020-04-27T12:02:46 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftereachmethod -->
        <test-method status="SKIP" signature="logout()[pri:2, instance:testcases.ApplicationTest@4f970963]" name="logout" duration-ms="0" started-at="2020-04-27T12:02:46 CDT" depends-on-methods="testcases.ApplicationTest.doLogin" finished-at="2020-04-27T12:02:46 CDT">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ApplicationTest.logout()[pri:2, instance:testcases.ApplicationTest@4f970963] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ApplicationTest.logout()[pri:2, instance:testcases.ApplicationTest@4f970963] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="afterallTest()[pri:0, instance:testcases.ApplicationTest@4f970963]" name="afterallTest" is-config="true" duration-ms="1" started-at="2020-04-27T12:02:46 CDT" finished-at="2020-04-27T12:02:46 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterallTest -->
      </class> <!-- testcases.ApplicationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
