<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Arjuns-MBP.attlocal.net" ignored="0" name="Application Test" tests="5" failures="1" timestamp="2020-04-25T23:21:11 CDT" time="0.054" errors="0">
  <testcase name="doLogin" time="0.006" classname="testcases.LoginTest"/>
  <testcase name="doLogin" time="0.002" classname="testcases.LoginTest"/>
  <testcase name="doLogin" time="0.001" classname="testcases.LoginTest"/>
  <testcase name="doLogin" time="0.01" classname="testcases.ApplicationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error message">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error message
at testcases.ApplicationTest.doLogin(ApplicationTest.java:23)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
  <testcase name="logout" time="0.0" classname="testcases.ApplicationTest">
    <skipped/>
  </testcase> <!-- logout -->
</testsuite> <!-- Application Test -->
